### ISSUE TITLE
sun disk broken with reverse z

### ISSUE THREAD

**Issue by shakesoda** [BastiaanOlij/RERadialSunRays#1]
hi, thanks for the great demo.

i noticed when trying to use this as reference that i wasn't getting anything in 4.3 beta 1, after some digging it turned out to be these lines: https://github.com/BastiaanOlij/RERadialSunRays/blob/master/radial_sky_rays/make_sun_disk.glsl#L36-L37

changing to `1.0 - depth` fixed it up for me

**Comment by BastiaanOlij** [comment]
Good catch, thanks for pointing it out :)
